#!/bin/sh
# This script source ros2 related environment vars

if test $# -eq 0; then
  echo -e "Please provide ros2 distro version, foxy, galactic, humble..."
  echo -e "For example:"
  echo -e "source ros2_env humble"
  return 1
fi

SCRIPT_EXTENSION=""
EXTRA_SETUP="false"
if test -n "$ZSH_VERSION"; then
  SCRIPT_EXTENSION="zsh"
  EXTRA_SETUP="true"
elif test -n "$BASH_VERSION"; then
  SCRIPT_EXTENSION="bash"
fi

source /opt/ros/$1/setup.$SCRIPT_EXTENSION

source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.$SCRIPT_EXTENSION
source /usr/share/colcon_cd/function/colcon_cd.sh

source /usr/share/gazebo/setup.sh

if [[ $EXTRA_SETUP == "true" ]]
then
  eval "$(register-python-argcomplete3 ros2)"
  eval "$(register-python-argcomplete3 colcon)"
fi

export RCUTILS_COLORIZED_OUTPUT=1
export ROS_DOMAIN_ID=0
