#!/bin/sh
# This script source ros2 related environment vars

if test $# -eq 0; then
  echo -e "The available distros are:\n=========================="
  ls /opt/ros/ | grep -E 'dashing|eloquent|foxy|galactic|humble|iron'
  echo -e "\nFor example:\n============"
  echo -e "source ros2_env humble"
  return 1
fi

SCRIPT_EXTENSION=""
EXTRA_SETUP="false"
if test -n "$ZSH_VERSION"; then
  SCRIPT_EXTENSION="zsh"
  EXTRA_SETUP="true"
  autoload -U +X bashcompinit && bashcompinit
elif test -n "$BASH_VERSION"; then
  SCRIPT_EXTENSION="bash"
fi

source /opt/ros/$1/setup.$SCRIPT_EXTENSION
# Source setup if it's a workspace
# script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
script_dir="$PWD" # What a simple solution!
if [[ -f "$script_dir/install/setup.$SCRIPT_EXTENSION" ]]; then
  echo "Workspace sourced!"
  source $script_dir/install/setup.$SCRIPT_EXTENSION
fi

# gazebo classic no longer exist
# source /usr/share/gazebo/setup.sh

if [[ $EXTRA_SETUP == "true" && $ROS_DISTRO != "jazzy" ]]
then
  eval "$(register-python-argcomplete3 ros2)"
  eval "$(register-python-argcomplete3 colcon)"

  # source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.$SCRIPT_EXTENSION
  # source /usr/share/colcon_cd/function/colcon_cd.sh
elif [[ $EXTRA_SETUP == "true" && $ROS_DISTRO == "jazzy" ]]
then
  eval "$(register-python-argcomplete ros2)"
  eval "$(register-python-argcomplete colcon)"
fi

export RCUTILS_COLORIZED_OUTPUT=1

ROS2_SETUP_PATH=$HOME/.config/p_aliases/ros2_setup
test -f $ROS2_SETUP_PATH && source $ROS2_SETUP_PATH
