#!/bin/sh
# To make ROS work

VERSION_ID=$(lsb_release -rs)
ROS_VERSION=''
if [[ $VERSION_ID == '18.04' ]]; then
  ROS_VERSION=melodic
elif [[ $VERSION_ID == '20.04' ]]; then
  ROS_VERSION=noetic
fi

SCRIPT_EXTENSION=''
if test -n "$ZSH_VERSION"; then
  SCRIPT_EXTENSION="zsh"
elif test -n "$BASH_VERSION"; then
  SCRIPT_EXTENSION="bash"
fi

source /opt/ros/$ROS_VERSION/setup.$SCRIPT_EXTENSION
source /usr/share/gazebo/setup.sh
# Source setup if it's a workspace
# script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
script_dir="$PWD" # What a simple solution!
if [[ -f "$script_dir/devel/setup.$SCRIPT_EXTENSION" ]]; then
  echo "Workspace sourced!"
  source $script_dir/devel/setup.$SCRIPT_EXTENSION
fi

ROS_SETUP_PATH=$HOME/.config/p_aliases/ros_setup
test -f $ROS_SETUP_PATH && source $ROS_SETUP_PATH
