#!/bin/sh
# To make ROS work

VERSION_ID=$(lsb_release -rs)
ROS_VERSION=''
if [[ $VERSION_ID == '18.04' ]]; then
  ROS_VERSION=melodic
elif [[ $VERSION_ID == '20.04' ]]; then
  ROS_VERSION=noetic
fi

SCRIPT_EXTENSION=''
if test -n "$ZSH_VERSION"; then
  SCRIPT_EXTENSION="zsh"
elif test -n "$BASH_VERSION"; then
  SCRIPT_EXTENSION="bash"
fi

source /opt/ros/$ROS_VERSION/setup.$SCRIPT_EXTENSION
source /usr/share/gazebo/setup.sh
# Source setup if it's a workspace
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
if [[ -f "$script_dir/devel/setup.$SCRIPT_EXTENSION" ]]; then
  echo "Workspace sourced!"
  source $script_dir/devel/setup.$SCRIPT_EXTENSION
fi

LOCAL_IP=$(hostname -I | awk {'print $1'})
export ROS_HOSTNAME=192.168.1.15

# LOCAL ROS MASTER
# export ROS_MASTER_URI=http://$LOCAL_IP:11311

# OTHER ROS MASTER
export ROS_MASTER_URI=http://192.168.1.153:11311
