#!/usr/bin/env bash
# This file holds the list for git user profiles

declare -A bri=( ["name"]="Brina Shong"  ["email"]="shongwtb@i2r.a-star.edu.sg" )
declare -A cjl=( ["name"]="Chan Jian Le" ["email"]="jianle001@e.ntu.edu.sg" )
declare -A nur=( ["name"]="Nursultan Imanberdiyev" ["email"]="nursultani@i2r.a-star.edu.sg" )
declare -A nxy=( ["name"]="Ng Xing Yu" ["email"]="ng_xing_yu@htx.gov.sg" )
declare -A eli=( ["name"]="Elizabeth Ng" ["email"]="elizabeth_ng@htx.gov.sg" )
declare -A ljm=( ["name"]="Liew Jia Min" ["email"]="liew_jia_min@htx.gov.sg" )
